dist: trusty
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: BV5M3CEw5TRCkjRREP7g43RaHQipFeh406SxVq4LLQ+MciUoMCrwRO/Z3O7Sy7amJI30RF7pj+1uVcbpqsVjjDSjSO9tTwbdjSyGPg7CgI6Az8s6+l0uD2m1ZCfWaaM84gIENO0smBkUcBKrm8MjCF+GCrCUB1HiUwzmvBv2+kCEY+MFhvs/CroIyBb5lhg0v25wvsMZ8hUXyjNyrJwaG65tw7QudjWsl4448JC7VVAeP8KTr/2RHL1NGfigFtPvS8MU8QBlPfZB+f445FmHLJN04Ql03yCQR9nlWO1GWf21RZtqxe5cAHT471pWHH6+E6q16WkOCPZ3Fn2Tbg2TxTOSZs6fb5fy1YEfDRJqpwfdF4miRk4/K/bGyWcunRoEyQjwC9SUT12Vpt6xRs07xU1vruofrBFHGsmIhVMrt2O9CTOuL4680JMFHimdZdNvzKGSF+JFu5IQq/q6MEOm8Wq9fHXOkKbG+LvRcLW7wdGLP1bj94dDYlx2zrQEtvmETi6b0DhNszRIEUK36UC/dcaXqKTz3jkCc43s8RIAkFRkSs/XSrONoZmdmPGW6s4YhwJHYczpY+QrX7TLsvlLPUPwviCt8kqQZly/zcvfM9HE2w6RN8hQ+E8uOoD3eV1z4ZGGgWz2Lge1F+TuO58UVL3AVWC/RaoR8gPmnsKMnPM=
